version: "3"

services:
  deply-now:
    container_name: deploy-now
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./src/logs.txt:/app/logs.txt
    labels:
      - deploy-now.enable=false
